// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SGEstudante.Infrastructure.Data;
using System;

namespace SGEstudante.Infrastructure.Migrations
{
    [DbContext(typeof(EstudanteContext))]
    [Migration("20180517214825_AdicionaClasseContato")]
    partial class AdicionaClasseContato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGEstudante.ApplicationCore.Entity.Contato", b =>
                {
                    b.Property<int>("ContatoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("EstudanteId");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("ContatoId");

                    b.HasIndex("EstudanteId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("SGEstudante.ApplicationCore.Entity.Estudante", b =>
                {
                    b.Property<int>("EstudanteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<int>("Incricao");

                    b.Property<string>("Nome");

                    b.HasKey("EstudanteId");

                    b.ToTable("Estudante");
                });

            modelBuilder.Entity("SGEstudante.ApplicationCore.Entity.Contato", b =>
                {
                    b.HasOne("SGEstudante.ApplicationCore.Entity.Estudante", "Estudante")
                        .WithMany("Contatos")
                        .HasForeignKey("EstudanteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
